version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: food_delivery_db
    environment:
      POSTGRES_USER: prankursharma
      POSTGRES_PASSWORD: "Prankur@2005"
      POSTGRES_DB: food_ordering_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
